-- 공용 코드
CREATE TABLE TB_CODE (
    CODE_ID      VARCHAR2(10) PRIMARY KEY NOT NULL,
    CODE_NAME    VARCHAR2(30),
    FLAG         INT,
    CREATED_DATE DATE DEFAULT SYSDATE,
    CREATED_ID   VARCHAR2(100),
    UPDATED_DATE DATE DEFAULT SYSDATE,
    UPDATED_ID   VARCHAR2(100)
);

-- 테이블 주석
COMMENT ON TABLE TB_CODE IS '공용 코드';

-- 컬럼 주석
COMMENT ON COLUMN TB_CODE.CODE_ID IS '코드 아이디';
COMMENT ON COLUMN TB_CODE.CODE_NAME IS '코드명';
COMMENT ON COLUMN TB_CODE.FLAG IS '구분값';
COMMENT ON COLUMN TB_CODE.CREATED_DATE IS '작성일자';
COMMENT ON COLUMN TB_CODE.CREATED_ID IS '작성자 ID';
COMMENT ON COLUMN TB_CODE.UPDATED_DATE IS '수정일자';
COMMENT ON COLUMN TB_CODE.UPDATED_ID IS '수정자 ID';

-- 마스터 코드 커스터 마이징

-- 부서
INSERT INTO TB_CODE VALUES ('DP_01', '하우스키핑', 0, SYSDATE, 'ADMIN', SYSDATE, 'ADMIN');
INSERT INTO TB_CODE VALUES ('DP_02', '시설관리', 0, SYSDATE, 'ADMIN', SYSDATE, 'ADMIN');
INSERT INTO TB_CODE VALUES ('DP_03', '프론트', 0, SYSDATE, 'ADMIN', SYSDATE, 'ADMIN');

-- 직책
INSERT INTO TB_CODE VALUES ('GR_01', '총지배인', 0, SYSDATE, 'ADMIN', SYSDATE, 'ADMIN');
INSERT INTO TB_CODE VALUES ('GR_02', '팀장', 0, SYSDATE, 'ADMIN', SYSDATE, 'ADMIN');
INSERT INTO TB_CODE VALUES ('GR_03', '일반', 0, SYSDATE, 'ADMIN', SYSDATE, 'ADMIN');

-- 객실종류
INSERT INTO TB_CODE VALUES ('TP_01', '스탠다드룸', 0, SYSDATE, 'ADMIN', SYSDATE, 'ADMIN');
INSERT INTO TB_CODE VALUES ('TP_02', '디럭스룸', 0, SYSDATE, 'ADMIN', SYSDATE, 'ADMIN');
INSERT INTO TB_CODE VALUES ('TP_03', '트윈룸', 0, SYSDATE, 'ADMIN', SYSDATE, 'ADMIN');
INSERT INTO TB_CODE VALUES ('TP_04', '패밀리룸', 0, SYSDATE, 'ADMIN', SYSDATE, 'ADMIN');
INSERT INTO TB_CODE VALUES ('TP_05', '스위트룸', 0, SYSDATE, 'ADMIN', SYSDATE, 'ADMIN');
INSERT INTO TB_CODE VALUES ('TP_06', '펜트하우스', 0, SYSDATE, 'ADMIN', SYSDATE, 'ADMIN');

-- 중요도
INSERT INTO TB_CODE VALUES ('IM_01', '낮음', 0, SYSDATE, 'ADMIN', SYSDATE, 'ADMIN');
INSERT INTO TB_CODE VALUES ('IM_02', '보통', 0, SYSDATE, 'ADMIN', SYSDATE, 'ADMIN');
INSERT INTO TB_CODE VALUES ('IM_03', '높음', 0, SYSDATE, 'ADMIN', SYSDATE, 'ADMIN');

-- 교대
INSERT INTO TB_CODE VALUES ('SH_01', '주간', 0, SYSDATE, 'ADMIN', SYSDATE, 'ADMIN');
INSERT INTO TB_CODE VALUES ('SH_02', '야간', 0, SYSDATE, 'ADMIN', SYSDATE, 'ADMIN');

-- 상태
INSERT INTO TB_CODE VALUES ('ST_00', '미완료', 0, SYSDATE, 'ADMIN', SYSDATE, 'ADMIN');
INSERT INTO TB_CODE VALUES ('ST_01', '완료', 0, SYSDATE, 'ADMIN', SYSDATE, 'ADMIN');
INSERT INTO TB_CODE VALUES ('ST_02', '진행중', 0, SYSDATE, 'ADMIN', SYSDATE, 'ADMIN');
INSERT INTO TB_CODE VALUES ('ST_03', '문제발생', 0, SYSDATE, 'ADMIN', SYSDATE, 'ADMIN');


-- 부서
-- DP_01 하우스키핑
-- DP_02 시설관리
-- DP_03 프론트

-- 직책
--GR_01 총지배인
--GR_02 팀장
--GR_03 일반

-- 객실종류
--TP_01 스탠다드룸
--TP_02 디럭스룸
--TP_03 트윈룸
--TP_04 패밀리룸
--TP_05 스위트룸
--TP_06 펜트하우스

-- 중요도
--IM_01 낮음
--IM_02 보통
--IM_03 높음

--교대
--SH_01 주간
--SH_02 야간

-- 상태
--ST_00 미완료
--ST_01 완료
--ST_02 진행중
--ST_03 문제발생