-- 직원 테이블
CREATE TABLE TB_EMPL (
    EMPL_ID      VARCHAR2(30) PRIMARY KEY NOT NULL,
    EMPL_NAME    VARCHAR2(50) NOT NULL,
    EMPL_PHONE   VARCHAR2(14),
    EMPL_DEPT    VARCHAR2(14) NOT NULL,
    EMPL_GRADE   VARCHAR2(10) NOT NULL,
    PHOTO_NAME   VARCHAR2(100),
    PHOTO_PATH   VARCHAR2(300),
    EMPL_NOTES   VARCHAR2(2000),
    CREATED_DATE DATE DEFAULT SYSDATE,
    CREATED_ID   VARCHAR2(100),
    UPDATED_DATE DATE DEFAULT SYSDATE,
    UPDATED_ID   VARCHAR2(100),
    RETIRED_YN   VARCHAR2(1) DEFAULT 'N' NOT NULL,
    COFFEE_WINNER_YN CHAR(1) DEFAULT 'N' NOT NULL;
);

-- 테이블 주석
COMMENT ON TABLE TB_EMPL IS '직원 관리용 테이블';

-- 컬럼 주석
COMMENT ON COLUMN TB_EMPL.EMPL_ID IS '직원 ID';
COMMENT ON COLUMN TB_EMPL.EMPL_NAME IS '직원명';
COMMENT ON COLUMN TB_EMPL.EMPL_PHONE IS '연락처';
COMMENT ON COLUMN TB_EMPL.EMPL_DEPT IS '부서 코드';
COMMENT ON COLUMN TB_EMPL.EMPL_GRADE IS '직책 코드';
COMMENT ON COLUMN TB_EMPL.PHOTO_NAME IS '사진 파일명';
COMMENT ON COLUMN TB_EMPL.PHOTO_PATH IS '사진 파일 경로';
COMMENT ON COLUMN TB_EMPL.EMPL_NOTES IS '메모';
COMMENT ON COLUMN TB_EMPL.CREATED_DATE IS '작성일자';
COMMENT ON COLUMN TB_EMPL.CREATED_ID IS '작성자 ID';
COMMENT ON COLUMN TB_EMPL.UPDATED_DATE IS '수정일자';
COMMENT ON COLUMN TB_EMPL.UPDATED_ID IS '수정자 ID';
COMMENT ON COLUMN TB_EMPL.RETIRED_YN IS '퇴사 여부 (Y: 퇴사, N: 재직)';
COMMENT ON COLUMN TB_EMPL.COFFEE_WINNER_YN IS '오늘의 커피 당첨 여부 (Y: 당첨, N: 미당첨)';

-- 처음 관리자 설정
INSERT INTO TB_EMPL VALUES
    (
        SUBSTR(LOWER(RAWTOHEX(SYS_GUID())),1,30),
        '관리자',
        '01012345678',
        'DP_01',
        'GR_01',
        '',
        '',
        '관리자입니다.',
        SYSDATE,
        'ADMIN',
        SYSDATE,
        'ADMIN',
        'N',
        'N'
    );