-- 공지사항 테이블
CREATE TABLE TB_NOTICE (
    NOTICE_ID      INT PRIMARY KEY NOT NULL,
    NOTICE_TITLE   VARCHAR2(50) NOT NULL,
    EMPL_ID        VARCHAR2(30) NOT NULL,
    NOTICE_CONTENT VARCHAR2(2000),
    CREATED_DATE   DATE DEFAULT SYSDATE,
    CREATED_ID     VARCHAR2(100),
    UPDATED_DATE   DATE DEFAULT SYSDATE,
    UPDATED_ID     VARCHAR2(100)
);

-- 테이블 주석
COMMENT ON TABLE TB_NOTICE IS '공지사항 테이블';

-- 컬럼 주석
COMMENT ON COLUMN TB_NOTICE.NOTICE_ID IS '공지 ID';
COMMENT ON COLUMN TB_NOTICE.NOTICE_TITLE IS '공지 제목';
COMMENT ON COLUMN TB_NOTICE.EMPL_ID IS '글쓴이';
COMMENT ON COLUMN TB_NOTICE.NOTICE_CONTENT IS '공지 내용';
COMMENT ON COLUMN TB_NOTICE.CREATED_DATE IS '작성일자';
COMMENT ON COLUMN TB_NOTICE.CREATED_ID IS '작성자 ID';
COMMENT ON COLUMN TB_NOTICE.UPDATED_DATE IS '수정일자';
COMMENT ON COLUMN TB_NOTICE.UPDATED_ID IS '수정자 ID';