-- 객실 테이블
CREATE TABLE TB_ROOM (
     ROOM_ID        VARCHAR2(20) PRIMARY KEY NOT NULL,
     ROOM_NAME      VARCHAR2(100) NOT NULL,
     ROOM_CLASS     VARCHAR2(10) NOT NULL,
     ROOM_CLASSNAME VARCHAR2(100) NOT NULL,
     CREATED_DATE   DATE DEFAULT SYSDATE,
     CREATED_ID     VARCHAR2(100),
     UPDATED_DATE   DATE DEFAULT SYSDATE,
     UPDATED_ID     VARCHAR2(100)
);

-- 테이블 주석
COMMENT ON TABLE TB_EMPL IS '객실 관리용 테이블';

-- 컬럼 주석
COMMENT ON COLUMN TB_ROOM.ROOM_ID IS '객실 ID';
COMMENT ON COLUMN TB_ROOM.ROOM_NAME IS '객실명';
COMMENT ON COLUMN TB_ROOM.ROOM_CLASS IS '객실 코드';
COMMENT ON COLUMN TB_ROOM.ROOM_CLASSNAME IS '객실 코드명';
COMMENT ON COLUMN TB_ROOM.CREATED_DATE IS '등록일자';
COMMENT ON COLUMN TB_ROOM.CREATED_ID IS '등록자 ID';
COMMENT ON COLUMN TB_ROOM.UPDATED_DATE IS '수정일자';
COMMENT ON COLUMN TB_ROOM.UPDATED_ID IS '수정자 ID';