-- 직원 스케줄(근무일정)
CREATE TABLE TB_SCHEDULE (
    SCHE_ID      VARCHAR2(20) PRIMARY KEY NOT NULL,
    SCHE_DATE    VARCHAR2(14),
    EMPL_ID      VARCHAR2(30),
    SCHE_SHIFT   VARCHAR2(10),
    CREATED_DATE DATE DEFAULT SYSDATE,
    CREATED_ID   VARCHAR2(100),
    UPDATED_DATE DATE DEFAULT SYSDATE,
    UPDATED_ID   VARCHAR2(100)
);

-- 테이블 주석
COMMENT ON TABLE TB_SCHEDULE IS '직원 스케줄(근무일정)';

-- 컬럼 주석
COMMENT ON COLUMN TB_SCHEDULE.SCHE_ID IS '업무 상세 ID';
COMMENT ON COLUMN TB_SCHEDULE.SCHE_DATE IS '업무 마스터 ID';
COMMENT ON COLUMN TB_SCHEDULE.EMPL_ID IS '업무명';
COMMENT ON COLUMN TB_SCHEDULE.SCHE_SHIFT IS '담당자 ID';
COMMENT ON COLUMN TB_SCHEDULE.CREATED_DATE IS '작성일자';
COMMENT ON COLUMN TB_SCHEDULE.CREATED_ID IS '작성자 ID';
COMMENT ON COLUMN TB_SCHEDULE.UPDATED_DATE IS '수정일자';
COMMENT ON COLUMN TB_SCHEDULE.UPDATED_ID IS '수정자 ID';