-- 업무 디테일 테이블
  CREATE TABLE "MOBY"."TB_WORK_D"
   (	"WORKD_ID" VARCHAR2(20 BYTE),
	"WORKM_ID" VARCHAR2(20 BYTE),
	"WORKD_NAME" VARCHAR2(50 BYTE),
	"EMPL_ID" VARCHAR2(30 BYTE),
	"WORKD_DEPT" VARCHAR2(10 BYTE),
	"WORKD_DATE" DATE,
	"WORKD_CONTEXT" VARCHAR2(2000 BYTE),
	"WORKD_EXTRA" VARCHAR2(2000 BYTE),
	"ROOM_ID" VARCHAR2(20 BYTE),
	"WORKD_IMPO" VARCHAR2(10 BYTE) DEFAULT 'IM_02',
    "WORKD_ISSUE" CHAR(1) DEFAULT 'N' CHECK (WORKD_ISSUE IN ('Y','N')),
	"ORDER_ID" VARCHAR2(30 BYTE),
	"START_NAME" VARCHAR2(100 BYTE),
	"START_TIME" DATE,
	"END_NAME" VARCHAR2(100 BYTE),
	"END_TIME" DATE,
	"CREATED_DATE" DATE DEFAULT SYSDATE,
	"CREATED_ID" VARCHAR2(100 BYTE),
	"UPDATED_DATE" DATE DEFAULT SYSDATE,
	"UPDATED_ID" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

-- 테이블 주석
COMMENT ON TABLE "MOBY"."TB_WORK_D"  IS '업무 디테일 테이블';

-- 컬럼 주석
   COMMENT ON COLUMN "MOBY"."TB_WORK_D"."WORKM_ID" IS '업무 마스터 ID';
   COMMENT ON COLUMN "MOBY"."TB_WORK_D"."WORKD_NAME" IS '업무명';
   COMMENT ON COLUMN "MOBY"."TB_WORK_D"."EMPL_ID" IS '담당자 ID';
   COMMENT ON COLUMN "MOBY"."TB_WORK_D"."WORKD_DEPT" IS '부서 코드';
   COMMENT ON COLUMN "MOBY"."TB_WORK_D"."WORKD_DATE" IS '업무 일자';
   COMMENT ON COLUMN "MOBY"."TB_WORK_D"."WORKD_CONTEXT" IS '업무 내용';
   COMMENT ON COLUMN "MOBY"."TB_WORK_D"."WORKD_EXTRA" IS '특이사항';
   COMMENT ON COLUMN "MOBY"."TB_WORK_D"."ROOM_ID" IS '객실 번호';
   COMMENT ON COLUMN "MOBY"."TB_WORK_D"."WORKD_IMPO" IS '중요도';
   COMMENT ON COLUMN "MOBY"."TB_WORK_D"."WORKD_ISSUE" IS '문제발생';
   COMMENT ON COLUMN "MOBY"."TB_WORK_D"."ORDER_ID" IS '지시자 ID';
   COMMENT ON COLUMN "MOBY"."TB_WORK_D"."START_NAME" IS '시작 사진 파일명';
   COMMENT ON COLUMN "MOBY"."TB_WORK_D"."START_TIME" IS '업무 시작 시간';
   COMMENT ON COLUMN "MOBY"."TB_WORK_D"."END_NAME" IS '종료 사진 파일명';
   COMMENT ON COLUMN "MOBY"."TB_WORK_D"."END_TIME" IS '업무 종료 시간';
   COMMENT ON COLUMN "MOBY"."TB_WORK_D"."CREATED_DATE" IS '작성일자';
   COMMENT ON COLUMN "MOBY"."TB_WORK_D"."CREATED_ID" IS '작성자 ID';
   COMMENT ON COLUMN "MOBY"."TB_WORK_D"."UPDATED_DATE" IS '수정일자';
   COMMENT ON COLUMN "MOBY"."TB_WORK_D"."UPDATED_ID" IS '수정자 ID';