-- 업무 디테일 테이블
CREATE TABLE TB_WORK_D (
    WORKD_ID      VARCHAR2(20) PRIMARY KEY NOT NULL,
    WORKM_ID      VARCHAR2(20) NOT NULL,
    WORKD_NAME    VARCHAR2(50) NOT NULL,
    EMPL_ID       VARCHAR2(30),
    WORKD_DEPT    VARCHAR2(10) NOT NULL,
    WORKD_DATE    DATE NOT NULL,
    WORKD_CONTEXT VARCHAR2(2000),
    WORKD_EXTRA   VARCHAR2(2000),
    ROOM_ID       VARCHAR2(20),
    WORKD_IMPO    VARCHAR2(10) DEFAULT 'IM_02' NOT NULL,
    WORKD_ISSUE   CHAR(1) DEFAULT 'N' CHECK ( WORKD_ISSUE IN ( 'Y', 'N' ) ),
    ORDER_ID      VARCHAR2(30),
    START_NAME    VARCHAR2(100),
    START_TIME    DATE,
    END_NAME      VARCHAR2(100),
    END_TIME      DATE,
    CREATED_DATE  DATE DEFAULT SYSDATE,
    CREATED_ID    VARCHAR2(100),
    UPDATED_DATE  DATE DEFAULT SYSDATE,
    UPDATED_ID    VARCHAR2(100)
);

-- 테이블 주석
COMMENT ON TABLE TB_WORK_D IS '업무 디테일 테이블';

-- 컬럼 주석
COMMENT ON COLUMN TB_WORK_D.WORKD_ID IS '업무 디테일 ID';
COMMENT ON COLUMN TB_WORK_D.WORKM_ID IS '업무 마스터 ID';
COMMENT ON COLUMN TB_WORK_D.WORKD_NAME IS '업무명';
COMMENT ON COLUMN TB_WORK_D.EMPL_ID IS '담당자 ID';
COMMENT ON COLUMN TB_WORK_D.WORKD_DEPT IS '부서 코드';
COMMENT ON COLUMN TB_WORK_D.WORKD_DATE IS '업무 일자';
COMMENT ON COLUMN TB_WORK_D.WORKD_CONTEXT IS '업무 내용';
COMMENT ON COLUMN TB_WORK_D.WORKD_EXTRA IS '특이사항';
COMMENT ON COLUMN TB_WORK_D.ROOM_ID IS '객실 번호';
COMMENT ON COLUMN TB_WORK_D.WORKD_IMPO IS '중요도';
COMMENT ON COLUMN TB_WORK_D.WORKD_ISSUE IS '문제발생';
COMMENT ON COLUMN TB_WORK_D.ORDER_ID IS '지시자 ID';
COMMENT ON COLUMN TB_WORK_D.START_NAME IS '시작 사진 파일명';
COMMENT ON COLUMN TB_WORK_D.START_TIME IS '업무 시작 시간';
COMMENT ON COLUMN TB_WORK_D.END_NAME IS '종료 사진 파일명';
COMMENT ON COLUMN TB_WORK_D.END_TIME IS '업무 종료 시간';
COMMENT ON COLUMN TB_WORK_D.CREATED_DATE IS '작성일자';
COMMENT ON COLUMN TB_WORK_D.CREATED_ID IS '작성자 ID';
COMMENT ON COLUMN TB_WORK_D.UPDATED_DATE IS '수정일자';
COMMENT ON COLUMN TB_WORK_D.UPDATED_ID IS '수정자 ID';