-- 업무 마스터 테이블
CREATE TABLE TB_WORK_M (
    WORKM_ID      VARCHAR2(20) PRIMARY KEY NOT NULL,
    WORKM_NAME    VARCHAR2(50) NOT NULL,
    WORKM_DEPT    VARCHAR2(10) NOT NULL,
    WORKM_CONTEXT VARCHAR2(2000),
    WORKM_IMPO    VARCHAR2(10) DEFAULT 'IM_02' NOT NULL,
    CREATED_DATE  DATE DEFAULT SYSDATE,
    CREATED_ID    VARCHAR2(100),
    UPDATED_DATE  DATE DEFAULT SYSDATE,
    UPDATED_ID    VARCHAR2(100)
);

-- 테이블 주석
COMMENT ON TABLE TB_WORK_M IS '업무 마스터 테이블';

-- 컬럼 주석
COMMENT ON COLUMN TB_WORK_M.WORKM_ID IS '업무 ID';
COMMENT ON COLUMN TB_WORK_M.WORKM_NAME IS '업무명';
COMMENT ON COLUMN TB_WORK_M.WORKM_DEPT IS '부서 코드';
COMMENT ON COLUMN TB_WORK_M.WORKM_CONTEXT IS '업무 내용';
COMMENT ON COLUMN TB_WORK_M.WORKM_IMPO IS '중요도';
COMMENT ON COLUMN TB_WORK_M.CREATED_DATE IS '작성일자';
COMMENT ON COLUMN TB_WORK_M.CREATED_ID IS '작성자 ID';
COMMENT ON COLUMN TB_WORK_M.UPDATED_DATE IS '수정일자';
COMMENT ON COLUMN TB_WORK_M.UPDATED_ID IS '수정자 ID';